yarnPath: ".yarn/releases/yarn-berry.cjs"

pnpMode: strict

packageExtensions:
  'react-scripts@*':
    dependencies:
      eslint-plugin-prettier: '*'
  'sass-loader@*':
    dependencies:
      sass: '*'
  typeorm@*:
    dependencies:
      events: '*'
      pg: '*'
