yarnPath: ".yarn/releases/yarn-berry.cjs"

pnpMode: strict

packageExtensions:
  'react-scripts@*':
    dependencies:
      eslint-plugin-prettier: '*'
  'sass-loader@*':
    dependencies:
      sass: '*'
  'redux-saga-test-plan@*':
    dependencies:
      '@redux-saga/is': '*'
      '@redux-saga/symbols': '*'
  typeorm@*:
    dependencies:
      events: '*'
      pg: '*'
