name: rest-mood-tracker

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/rest-mood-tracker.yaml'
      - 'packages/backend/rest-mood-tracker/**'

  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/rest-mood-tracker.yaml'
      - 'packages/backend/rest-mood-tracker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn workspace rest-mood-tracker lint
      - name: Build
        run: yarn workspace rest-mood-tracker build
